bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install libidn11-dev
  - gem update --system --no-document
  - gem install bundler --no-document

rvm: 2.4.9
script: bundle exec rake profile:memory
env:
  matrix:
    - IDNA_MODE=native
    - IDNA_MODE=pure
