bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - jruby-9.2.11.1
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
matrix:
  include:
    - rvm: 2.4.9
      script: bundle exec rake profile:memory
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
  fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install libidn11-dev
  # https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - if [ -n "${BUNDLER_VERSION+x}" ];
    then
      gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true;
      gem uninstall --all --executables bundler || true;
      gem install bundler -v ${BUNDLER_VERSION};
    fi
