bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - jruby-9.2.11.1
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
matrix:
  include:
    - rvm: 2.4.9
      env: IDNA_MODE=native
      script: bundle exec rake profile:memory
    - rvm: 2.4.9
      env: IDNA_MODE=pure
      script: bundle exec rake profile:memory
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
  fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install libidn11-dev
  - gem update --system --no-document
  - gem install bundler --no-document
